### PR TITLE
Update Readme.md (Pyro 2.1.1 crashes if a config from 1.4.1 is present.)

### PR DESCRIPTION
**Pull request by Intel-i80486-DX4**

### CODE REVIEW

**Comment by mr-nv** [comment]
wtf real shit?

**Comment by Intel-i80486-DX4** [comment]
it appears to be an inconsistent problem. (it happened the first time for me, it now appears to work with 1.4.1 configs???)

**Comment by Intel-i80486-DX4** [comment]
i'll edit it accordingly

**Comment by mr-nv** [comment]
ok if anyone else is gonna have this exact issue ill add a warning to the
readme

вс, 26 июн. 2022 г., 14:40 Intel-i80486-DX4 ***@***.***>:

**Comment by GentlemanMC** [comment]
(i do)
i replaced the 2.1.1 config folder with the 1.4.1 folder and it crashed

**Comment by mr-nv** [comment]
ok

чт, 30 июн. 2022 г., 15:25 Gentleman ***@***.***>:

**Pull request closed without merging**
